In [6]:
import numpy as np

world_alcohol = np.genfromtxt('world_alcohol.txt',delimiter=',',dtype=str)
print(type(world_alcohol))
print(world_alcohol)
#print(help(numpy.genfromtxt))

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


## numpy.array()创建矩阵

In [7]:
vector = np.array([1,2,3,4])
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(vector)
print(matrix)

[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## .shape()打印矩阵形状

In [11]:
print(vector.shape)
print(matrix.shape)

(4,)
(3, 3)


## .dtype打印元素类型，所有元素转为同一类型

In [12]:
numbers = np.array([1,2,3,'4'])
print(numbers)
numbers.dtype

['1' '2' '3' '4']


dtype('<U11')

## 元素整体操作

In [13]:
vector == 10

array([False, False, False, False])

In [14]:
matrix == 3

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

## 索引

In [15]:
world_alcohol = np.genfromtxt('world_alcohol.txt',delimiter = ',',dtype = 'U75',skip_header = 1)
third_country = world_alcohol[2,2]
print(third_country)

Cte d'Ivoire


## 布尔值索引

In [17]:
equal_to_7 = (matrix == 7)
print(matrix[equal_to_7])

[7]


In [18]:
second_column_8 = (matrix[:,1] == 8)
print(second_column_8)
print(matrix[second_column_8,:])

[False False  True]
[[7 8 9]]


In [20]:
vector = numpy.array([5,10,15,20])
equal_to_ten_and_five = (vector == 5) & (vector ==10)
print(equal_to_ten_and_five)
equal_to_ten_or_five = (vector == 5) | (vector ==10)
print(equal_to_ten_or_five)

[False False False False]
[ True  True False False]


## .astype元素类型转换

In [26]:
print(vector.dtype)
vector = vector.astype(float)
print(vector.dtype)

int32
float64


## 矩阵的属性

In [27]:
vector.min()

5.0

In [30]:
#列方向求和
matrix.sum(axis=0)

array([12, 15, 18])

In [31]:
#行方向求和
matrix.sum(axis=1)

array([ 6, 15, 24])

In [36]:
print(np.arange(15))
print(np.arange(15).reshape(3,5))
print(np.arange(15).reshape(3,5).ndim) #打印矩阵维度

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2


In [38]:
np.zeros((3,4))#以元组形式传入

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [40]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [41]:
np.random.random((2,3))

array([[0.68892326, 0.95446617, 0.50734099],
       [0.14817281, 0.30425545, 0.28987196]])

In [44]:
from numpy import pi
np.linspace(0,2*pi,10)

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

## 数学运算

In [48]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a)
print(b)
print(a < 25)
print(b ** 2)
print(a - b)
print(b - 1)
print(np.exp(b))
print(np.sqrt(b))

[10 20 30 40]
[0 1 2 3]
[ True  True False False]
[0 1 4 9]
[10 19 28 37]
[-1  0  1  2]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]


In [47]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
print(A * B)         #对应位置相乘
print(A.dot(B))      #矩阵乘法

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


## .floor 向下取整

In [49]:
a = np.floor(10 * np.random.random((3,4)))  #向下取整
print(a)

[[9. 6. 7. 5.]
 [9. 3. 9. 9.]
 [1. 5. 1. 6.]]


## .ravel拉平操作

In [50]:
print(a.ravel())

[9. 6. 7. 5. 9. 3. 9. 9. 1. 5. 1. 6.]


In [51]:
a.reshape(3,-1)  #-1表示忽略

array([[9., 6., 7., 5.],
       [9., 3., 9., 9.],
       [1., 5., 1., 6.]])

## 拼接操作

In [52]:
a = 10 * np.random.random((2,2))
b = 10 * np.random.random((2,2))
print(a)
print(b)
print(np.hstack((a,b)))   #横向拼接
print(np.vstack((a,b)))   #纵向拼接

[[8.6031809  8.30895391]
 [4.32574887 3.76089312]]
[[0.98055058 8.38879906]
 [5.83035089 0.16411566]]
[[8.6031809  8.30895391 0.98055058 8.38879906]
 [4.32574887 3.76089312 5.83035089 0.16411566]]
[[8.6031809  8.30895391]
 [4.32574887 3.76089312]
 [0.98055058 8.38879906]
 [5.83035089 0.16411566]]


## 切分操作

In [56]:
a = np.arange(24).reshape((2,12))
print(a)
print(np.hsplit(a,3))   #横向切割

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])]


In [57]:
print(np.hsplit(a,(3,4)))  #指定位置切割

[array([[ 0,  1,  2],
       [12, 13, 14]]), array([[ 3],
       [15]]), array([[ 4,  5,  6,  7,  8,  9, 10, 11],
       [16, 17, 18, 19, 20, 21, 22, 23]])]


In [58]:
print(np.vsplit(a.T,3))

[array([[ 0, 12],
       [ 1, 13],
       [ 2, 14],
       [ 3, 15]]), array([[ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19]]), array([[ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23]])]


## 复制操作

In [66]:
a = np.arange(12)
b = a              #浅赋值
b is a
#print(id(a))
#print(id(b))

True

In [65]:
c = a.view()      #浅赋值
c is a

False

In [62]:
d = a.copy()
d is a

False

## 找最大值

In [69]:
data = np.sin(np.arange(20)).reshape(5,4)
print(data)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]


In [73]:
ind = data.argmax(axis=0)   #返回列方向最大值的索引
print(ind)

[2 0 3 1]


In [72]:
data_max = data[ind,range(data.shape[1])]
print(data_max)

[0.98935825 0.84147098 0.99060736 0.6569866 ]


## .tile()矩阵扩展

In [77]:
a = np.arange(0,40,10)
print(a)
b = np.tile(a,(3,5))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


## .sort()排序

In [78]:
a = np.array([[4,3,5],[1,2,1]])
print(a)
print(np.sort(a,axis=1))    #行方向排序


[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]


In [80]:
a = np.array([4,3,1,2])
j = np.argsort(a)
print(j)    #返回排序后的索引
print(a[j])

[2 3 1 0]
[1 2 3 4]
